from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pyautogui
from selenium.webdriver.common.action_chains import ActionChains

driver = webdriver.Chrome()
driver.get("https://demoqa.com/")
driver.maximize_window()
driver.find_element(By.XPATH,"//h5[contains(.,'Elements')]").click()
driver.find_element(By.XPATH,"//li[@class='btn btn-light '][contains(.,'Text Box')]").click()
driver.find_element(By.XPATH,"//input[contains(@placeholder,'Full Name')]").send_keys("felipe mendonça")
driver.find_element(By.XPATH,"//input[contains(@placeholder,'name@example.com')]").send_keys("estavaoferreira@gmail.com")
driver.find_element(By.XPATH,"//textarea[contains(@placeholder,'Current Address')]").send_keys("rua 18 quadra 43")
driver.find_element(By.XPATH,"//textarea[contains(@id,'permanentAddress')]").send_keys("rua 18 quadra 43")
driver.find_element(By.XPATH,"//button[@type='button'][contains(.,'Submit')]").click()
teste  = (driver.find_element(By.ID, "name").text)
teste1 = (driver.find_element(By.ID, "email").text)
teste2 = (driver.find_element(By.XPATH, "(//p[contains(@class,'mb-1')])[3]").text)
teste3 = (driver.find_element(By.XPATH, "(//p[contains(@class,'mb-1')])[4]").text)
#driver.save_screenshot("imgs/imgs.png")#
#################### CAIXA DE CHECKBOX #################
driver.find_element(By.XPATH,"//li[@class='btn btn-light '][contains(.,'Check Box')]").click()
driver.find_element(By.XPATH,"//button[contains(@aria-label,'Expand all')]").click()
driver.find_element(By.XPATH,"//label[@for='tree-node-excelFile'][contains(.,'Excel File.doc')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Word File.doc')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'General')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Classified')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Private')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Public')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Veu')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Angular')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'React')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Commands')]").click()
driver.find_element(By.XPATH,"//span[@class='rct-title'][contains(.,'Notes')]").click()
time.sleep(1)

resultados_checkbox = (driver.find_element(By.ID,"result").text)
######################## RADIO BUTTON ########################
driver.find_element(By.XPATH,"//li[@class='btn btn-light '][contains(.,'Radio Button')]").click()
driver.find_element(By.XPATH,"//label[@class='custom-control-label'][contains(.,'Impressive')]").click()
teste5 = (driver.find_element(By.XPATH,"//p[@class='mt-3'][contains(.,'You have selected Impressive')]")).text
######################## WEB TABLES ########################
driver.find_element(By.ID,"item-3").click()
driver.find_element(By.ID,"addNewRecordButton").click()
driver.find_element(By.XPATH,"//input[contains(@placeholder,'First Name')]").send_keys("dfjdsdf")
driver.find_element(By.ID,"lastName").send_keys("dfjdsdsdsfdssff")
driver.find_element(By.ID,"userEmail").send_keys("dfsj@gmail.com")
driver.find_element(By.ID,"age").send_keys("2")
driver.find_element(By.ID,"salary").send_keys("2310")
driver.find_element(By.ID,"department").send_keys("teste")
driver.find_element(By.ID,"submit").click()
time.sleep(1)
######################## BUTTONS ########################
driver.find_element(By.ID,"item-4").click()
time.sleep(1)
### DOUBLE CLICK###
element_DC = driver.find_element(By.ID,"doubleClickBtn")
action = ActionChains(driver)
action.double_click(element_DC).perform()
driver.find_element(By.ID,"rightClickBtn")
##click button right###
element_RC = driver.find_element(By.ID,"rightClickBtn")
action.context_click(element_RC).perform()
time.sleep(1)
driver.find_element(By.XPATH,"(//button[contains(.,'Click Me')])[3]").click()
#########LINKS#########
driver.find_element(By.ID,"item-5").click()
time.sleep(1)
driver.find_element(By.ID,"simpleLink").click()
time.sleep(1)
###back to last TAB###
driver.switch_to.window(driver.window_handles[0])
time.sleep(2)
driver.find_element(By.ID,"dynamicLink").click()
time.sleep(1)
driver.switch_to.window(driver.window_handles[0])
time.sleep(2)
driver.find_element(By.ID,"created").click()
time.sleep(1)
driver.find_element(By.ID,"item-6").click()
driver.find_element(By.XPATH,"//a[contains(.,'Click Here for Valid Link')]").click()
time.sleep(1)
### VOLTAR UMA PÁGINA
driver.execute_script("window.history.go(-1)")
driver.find_element(By.XPATH,"//a[contains(.,'Click Here for Broken Link')]").click()
time.sleep(1)
driver.execute_script("window.history.go(-1)")
driver.find_element(By.ID,"item-7").click()
time.sleep(1)
driver.find_element(By.ID,"downloadButton").click()
time.sleep(1)
### scroll para baixo ###
driver.execute_script("window.scrollTo(0, 200)")
#driver.find_element(By.ID,"uploadFile").send_keys("teste.PNG")
driver.find_element(By.ID,"item-8").click()
time.sleep(6)
driver.find_element(By.XPATH,"//div[@class='header-wrapper'][contains(.,'Elements')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//div[@class='header-wrapper'][contains(.,'Forms')]").click()
time.sleep(2)
driver.find_element(By.XPATH,"//li[@class='btn btn-light '][contains(.,'Practice Form')]").click()
driver.find_element(By.ID,"firstName").send_keys("dfksf")
driver.find_element(By.ID,"lastName").send_keys("dfkdfsfsf")
driver.find_element(By.ID,"userEmail").send_keys("fddsfd4@gmail.com")
driver.find_element(By.XPATH,"//label[@for='gender-radio-2'][contains(.,'Female')]").click()
time.sleep(1)
driver.find_element(By.ID,"userNumber").send_keys("0123456789")
time.sleep(1)
driver.find_element(By.ID,"dateOfBirthInput").click()
time.sleep(1)
driver.find_element(By.XPATH,"//select[contains(@class,'react-datepicker__year-select')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//option[@value='1943'][contains(.,'1943')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//select[contains(@class,'react-datepicker__month-select')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//option[@value='7'][contains(.,'August')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//div[@class='react-datepicker__day react-datepicker__day--019'][contains(.,'19')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//div[contains(@class,'subjects-auto-complete__value-container subjects-auto-complete__value-container--is-multi css-1hwfws3')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//label[@for='hobbies-checkbox-1'][contains(.,'Sports')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//label[@for='hobbies-checkbox-2'][contains(.,'Reading')]").click()
time.sleep(1)
driver.find_element(By.XPATH,"//label[@for='hobbies-checkbox-3'][contains(.,'Music')]").click()
time.sleep(1)
driver.find_element(By.ID,"currentAddress").send_keys("fhsdfdshfsdfsjffhsf rua")
time.sleep(1)
driver.execute_script("window.scrollTo(0, 100)")
ad1= driver.find_element(By.XPATH,"//img[contains(@alt,'adplus-dvertising')]")
if ad1.is_displayed():
    print("anuncios encontrado!")
    driver.find_element(By.XPATH,"//div[@class='header-text'][contains(.,'Alerts, Frame & Windows')]").click()
    time.sleep(1)
else:
    print("deu erro")
driver.find_element(By.XPATH,"//li[@class='btn btn-light '][contains(.,'Browser Windows')]").click()
driver.find_element(By.ID,"tabButton").click()
time.sleep(2)
driver.switch_to.window(driver.window_handles[0])
time.sleep(1)
driver.find_element(By.ID,"windowButton").click()
time.sleep(1)
driver.switch_to.window(driver.window_handles[0])
time.sleep(1)
driver.find_element(By.ID,"messageWindowButton").click()
time.sleep(1)
driver.switch_to.window(driver.window_handles[0])
time.sleep(1)
driver.find_element(By.XPATH,"//li[@class='btn btn-light '][contains(.,'Alerts')]").click()
time.sleep(1)
driver.find_element(By.ID,"alertButton").click()
time.sleep(1)
###### CLICAR EM OK EM UM ALERT ###### 
WebDriverWait(driver, 2).until(EC.alert_is_present())
driver.switch_to.alert.accept()
time.sleep(2)
driver.find_element(By.ID,"timerAlertButton").click()
WebDriverWait(driver, 6).until(EC.alert_is_present())
driver.switch_to.alert.accept()
time.sleep(1)
driver.find_element(By.ID,"confirmButton").click()
time.sleep(1)
WebDriverWait(driver, 2).until(EC.alert_is_present())
time.sleep(1)
driver.switch_to.alert.accept()
time.sleep(1)
driver.find_element(By.ID,"promtButton").click()
WebDriverWait(driver, 2).until(EC.alert_is_present())
time.sleep(1)
driver.switch_to.alert.accept()
time.sleep(1)